Fix path to diffoscope used to generate Recommends
Let's add a sanity check so this will not happen again while we are at it.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -13,8 +13,10 @@ override_dh_auto_build:
 	dh_auto_build -O--buildsystem=pybuild
 
 override_dh_gencontrol:
-	echo "diffoscope:Recommends=$$(./diffoscope.py --list-tools | tail -n 1 | \
-		sed -e 's/\(^\| \)\(coreutils\|diffutils\|e2fsprogs\|findutils\|gzip\)\(,\|$$\)//g')" >> debian/diffoscope.substvars
+	TOOLS="$$(bin/diffoscope --list-tools | tail -n 1 | \
+		sed -e 's/\(^\| \)\(coreutils\|diffutils\|e2fsprogs\|findutils\|gzip\)\(,\|$$\)//g')"; \
+		[ -n "$$TOOLS" ] || { echo '--list-tools failed' >&2; exit 1; }; \
+		echo "diffoscope:Recommends=$$TOOLS" >> debian/diffoscope.substvars
 	dh_gencontrol -O--buildsystem=pybuild
 
 debian/diffoscope.1: debian/diffoscope.1.rst
